---
# tasks file for create_local_users

- name: getting user_list.yml from private vars repo
  block: 
  - name: cloning private repo
    local_action:
      module: ansible.builtin.git
      repo: "{{ private_repo_url }}"
      dest: private_repo
      update: yes

  - name: including variable cloned 
    include_vars:
      file: private_repo/vars/user_list.yml

  - debug:
      var: user_list


