---
# tasks file for create_local_users
- name: block to create users and add wheel 
  block:
  - name: creating users
    ansible.builtin.user:
      name: "{{ item }}"
    loop: "{{ user_list }}"

  - name: add users to the wheel group
    ansible.builtin.user:
      name: "{{ item }}"
      append: yes
      group: wheel 
    loop: "{{ user_list }}"
  become: yes

