---
- hosts: nuclab.fritz.box

  vars_files: 
    - local_vars/private_repo_url.yml

  roles:
    - role: dnsmasq
      become: yes

    - role: base_packages
      become: yes

    - role: create_local_users
    
