---
- hosts: localhost

  vars_files: 
    - local_vars/private_repo_url.yml

  roles:
    - role: nuclab.basics.base_packages
      become: yes

    - role: nuclab.basics.dnsmasq
      become: yes

    - role: nuclab.basics.create_local_users
   
    - role: nuclab.basics.content_hub_connect

    # for the nfs_server role, see: https://github.com/oasis-roles/ansible_collection_system/tree/master/roles/nfs_server
    - role: oasis_roles.system.nfs_server
      nfs_server_shares:
        - share_path: /opt/nuclab/rhv_nfs
          host_allow: '*'
          opts: rw
          create_dir: true
          group: wheel
          mode: '0775'
      nfs_server_services:
        - nfs-server
        - rpcbind 
