collections:
  - name: https://github.com/mariuslapagna/nuclab.git
    type: git

  # for the nfs_server role, see: https://github.com/oasis-roles/ansible_collection_system/tree/master/roles/nfs_server
  - name: https://github.com/oasis-roles/ansible_collection_system
    type: git