---
- hosts: host0.nuclab.network
  become: yes

  vars_files: 
    - custom_vars/user_list.yml
    - custom_vars/network.yml
    - custom_vars/rh_secrets.yml
    - custom_vars/contenthub_token.yml
    - custom_vars/rhv_secrets.yml

  roles:
    - role: base_packages
    - role: create_local_users
    - role: dnsmasq
    - role: content_hub_connect
    - role: oasis_roles.system.nfs_server
      nfs_server_shares:
        - share_path: /opt/nuclab/rhv_nfs
          host_allow: '*'
          opts: rw
          create_dir: true
          group: wheel
          mode: '0775'
      nfs_server_services:
        - nfs-server
        - rpcbind
    - role: redhat.rhv.repositories
      ovirt_repositories_use_subscription_manager: True
    - role: redhat.rhv.hosted_engine_setup
      he_fqdn: rhvm0.nuclab.network
      he_domain_type: nfs
      he_storage_domain_addr: localhost
      he_storage_domain_path: /opt/nuclab/rhv_nfs

