---
- hosts: host0.nuclab.network
  vars_files: 
    - local_vars/private_repo_url.yml

  roles:
    - role: base_packages
      become: yes
    
    - role: dnsmasq
      become: yes

    - role: create_local_users
   
    - role: content_hub_connect

    - role: oasis_roles.system.nfs_server
      nfs_server_shares:
        - share_path: /opt/nuclab/rhv_nfs
          host_allow: '*'
          opts: rw
          create_dir: true
          group: wheel
          mode: '0775'
      nfs_server_services:
        - nfs-server
        - rpcbind 
